---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - impersonate
  - list
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - githubcomments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - githubcomments/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - githubcomments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitlabcomments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitlabcomments/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitlabcomments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitprojectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitprojectors/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - gitprojectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - listgithubpullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - listgithubpullrequests/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - listgithubpullrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - listgitlabmergerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - listgitlabmergerequests/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - listgitlabmergerequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - objecttemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - texttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - texttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.kluctl.io
  resources:
  - texttemplates/status
  verbs:
  - get
  - patch
  - update
